---
  name: Generate branch release
  permissions:
    security-events: write
    pull-requests: write
    packages: read
    actions: read
    contents: write
    deployments: write
    issues: write
    checks: write
    statuses: write # Used by CM to mark commit status
  on:
    workflow_dispatch:
      inputs:
        domain:
          description: "Domain"
          required: true
          type: choice
          options:
            - dominio1
            - dominio2
            - technology
        subdomain:
          description: 'Subdomain'
          required: true
          type: string
        destination:
          description: 'Destination'
          required: true
          type: string
        version_type:
          description: 'Version Type'
          required: true
          type: choice
          options:
            - patch
            - minor
            - major
        deploy_stg:
          type: boolean
          description: 'Deploy in STG'
          required: false
          
  
  run-name: Generate branch release [${{ inputs.domain }} / ${{ inputs.subdomain }} / ${{ inputs.destination }} ] Version type :${{ inputs.version_type }} by @${{ github.actor }}
  
  env:
    PREFIX_REPO: '${{inputs.domain}}-${{inputs.subdomain}}-${{inputs.destination}}'

  jobs:
    get_release_candidate:
      uses: nriofrio2508/my_reusable/.github/workflows/get_next_release_candidate.yaml@main
      with:
        prefix_repo: '${{inputs.domain}}-${{inputs.subdomain}}-${{inputs.destination}}'
        version_type: ${{inputs.version_type }}
      secrets: inherit

    create_branch:
      needs: get_release_candidate
      uses: nriofrio2508/my_reusable/.github/workflows/generate_release_branch.yaml@main
      with:
        branch_name: '${{ needs.get_release_candidate.outputs.next_rc }}'
      secrets: inherit
    
    deploy_stg:
      if: ${{ inputs.deploy_stg }}
      needs: ['create_branch']
      runs-on: ubuntu-latest
      steps:

        - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd #v5
          with:
            fetch-depth: 0

        - name: Call workflow New Release Flow Auto Version
          run: |
            gh workflow run release.yml  -f actor=${{ github.actor }} -f domain=${{ inputs.domain }} -f subdomain=${{ inputs.subdomain }} -f destination=${{ inputs.destination }} -f version_type=${{ inputs.version_type }} --ref=${{ needs.create_branch.outputs.release_branch_name}}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
          
        
