# This is a basic workflow to help you get started with Actions

name: Delete Tags

# Controls when the workflow will run
on:  
  workflow_dispatch:
  

jobs:
  # This workflow contains a single job called "build"

  validate_deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags
      - name: Delete release
        run: |
          gh release delete --cleanup-tag domain1_subdomain1_destino1-v5.2.0-rc.* domain1_subdomain1_destino1-v5.2.0-rc.* 
          