name: Generate Release

on:
  workflow_call:
    inputs:
      matrix_dominio:
        required: true
        type: string
      execute_matrix:
        required: true
        type: boolean

jobs:
  getReleaseFromJson:
    if: ${{ inputs.execute_matrix == true }}
    runs-on: ubuntu-latest
    outputs:
      last_tag_repo: ${{ steps.outputs_matrix.outputs.last_tag_repo }}
      next_tag_repo: ${{ steps.outputs_matrix.outputs.next_tag_repo}}
      last_stable_release: ${{ steps.outputs_matrix.outputs.last_stable_release}}
      domain: ${{ steps.outputs_matrix.outputs.domain}}
      subdomain: ${{ steps.outputs_matrix.outputs.subdomain}}
      destination: ${{ steps.outputs_matrix.outputs.destination}}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download blob reports from GitHub Actions Artifacts
        uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # v4.1.9
        with:
          name: ${{ inputs.matrix_dominio }}
      
      - name: Outputs 
        id: outputs_matrix
        run: |
          last_tag_repo=$(jq -r '.last_tag_repo' ${{ inputs.matrix_dominio }}.json)
          next_tag_repo=$(jq -r '.next_tag_repo' ${{ inputs.matrix_dominio }}.json)
          last_stable_release=$(jq -r '.last_stable_release' ${{ inputs.matrix_dominio }}.json)
          echo "last_tag_repo=$last_tag_repo" >> $GITHUB_OUTPUT
          echo "next_tag_repo=$next_tag_repo" >> $GITHUB_OUTPUT
          echo "last_stable_release=$last_stable_release" >> $GITHUB_OUTPUT
          echo "domain=$(echo $next_tag_repo | cut -d'-' -f1)" >> $GITHUB_OUTPUT
          echo "subdomain=$(echo $next_tag_repo | cut -d'-' -f2)" >> $GITHUB_OUTPUT
          echo "destination=$(echo $next_tag_repo | cut -d'-' -f3)" >> $GITHUB_OUTPUT

  generateRelease:
    needs: getReleaseFromJson
    uses: nriofrio2508/my_reusable/.github/workflows/generate_pre_release.yml
    with:
      execute_matrix: ${{ inputs.execute_matrix }}
      matrix_dominio: ${{ inputs.matrix_dominio }}
    secrets: inherit