name: Merge QA
on:
  workflow_dispatch:

jobs:
  merge_qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: merge branch
        run: |
          echo "Current Branch: ${{ github.ref_name }}"
          branch_origin="${{ github.ref_name }}"
          git checkout qa 
          git pull
          git merge $branch_origin
          git push origin qa
          echo "Finalizo merge"