name: Merge QA
on:
  workflow_dispatch:

jobs:
  merge_qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: qa
      
      - name: merge branch
        run: |
          echo "Current Branch: ${{ github.ref_name }}"
          git pull
          git merge ${{ github.ref_name }}
          git push origin qa
          echo "Finalizo merge"