# This is a basic workflow to help you get started with Actions

name: Pull Request

# Controls when the workflow will run
on:  
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]
    
jobs:
    create_branch:
        runs-on: ubuntu-latest
        steps:
            - uses: peterjgrainger/action-create-branch@v2.2.0
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                branch: 'release-notes'