# This is a basic workflow to help you get started with Actions

name: Deploy release

# Controls when the workflow will run
on:  
  workflow_dispatch:
    inputs:
      domain:
        description: 'Domain'
        required: true
        type: choice
        options:
          - domain1
          - domain2
          - domain3
        default: 'domain1'

      subdomain:
        description: 'Subdomain'
        required: true
        type: string
        default: 'subdomain1'     

      destino:
        description: 'Destino'
        required: true
        type: string
        default: 'destino1'  
      
      tipo_cambio:
        description: 'Seleccione tipo cambio'
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"

  validate_deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Validate deploy Step
        run: echo "Validate deploy OK"

  get_last_tag:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: validate_deploy
    outputs:
      last_tag_repo: ${{steps.previoustag.outputs.tag}}
      next_tag_repo: ${{ steps.increment_tag_rc.outputs.new_rc_version || steps.generate_tag_rc.outputs.new_rc_version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags
      
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          prefix: '${{inputs.domain}}_${{inputs.subdomain}}_${{inputs.destino}}-v'
          fallback: '${{inputs.domain}}_${{inputs.subdomain}}_${{inputs.destino}}-v0.0.0' # Optional fallback tag to use when no tag can be found
      - name: Get last tag Step
        run: echo "Get last tag OK ${{ steps.previoustag.outputs.tag }}"
      
      - name: Evaluar tag
        id: evaluar_tag
        run: |
          resultado=$(echo ${{ steps.previoustag.outputs.tag }} | awk -F'-rc.' '{print $2}')
          if [ $resultado != '' ]; then
            ((resultado++))            
          fi
          echo "rc_version=$resultado" >> $GITHUB_OUTPUT

      - name: Get only numbers version
        id: version_number_step
        if: ${{ steps.evaluar_tag.outputs.rc_version == ''}}
        run: |
          version_number=$(echo ${{ steps.previoustag.outputs.tag }} | awk -F'-v' '{print $2}')
          echo $version_number
          echo "version_number=$version_number" >> $GITHUB_OUTPUT
      
      - name: 'Get next minor version'
        id: semvers
        if: ${{ steps.evaluar_tag.outputs.rc_version == ''}}
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.version_number_step.outputs.version_number }}

      - name: Generate tag RC
        id: generate_tag_rc
        if: ${{ steps.evaluar_tag.outputs.rc_version == '' }}
        run: |
          new_rc_version="${{inputs.domain}}_${{inputs.subdomain}}_${{inputs.destino}}"
          case "${{inputs.tipo_cambio}}" in
              major)
                  echo "new_rc_version=$new_rc_version-v${{steps.semvers.outputs.major }}-rc.1"  >> $GITHUB_OUTPUT
                  ;;
              minor)
                  echo "new_rc_version=$new_rc_version-v${{steps.semvers.outputs.minor }}-rc.1"  >> $GITHUB_OUTPUT
                  ;;
              patch)
                  echo "new_rc_version=$new_rc_version-v${{steps.semvers.outputs.path }}-rc.1"  >> $GITHUB_OUTPUT
                  ;;
              *)
                  echo "$parametro no es major, minor, ni patch"
                  ;;
          esac
          echo new_rc_version
                
      - name: Increment tag RC
        id: increment_tag_rc
        if: ${{ steps.evaluar_tag.outputs.rc_version != '' }}
        run: |
          new_rc_version=$(echo "${{ steps.previoustag.outputs.tag }}" | sed "s/-rc\..*/-rc.${{ steps.evaluar_tag.outputs.rc_version }}/")
          echo "Mi nueva version=$new_rc_version"
          echo "new_rc_version=$new_rc_version" >> $GITHUB_OUTPUT

      
        
        
  generate_pre_release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: get_last_tag
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push new Tag ReleaseCandidate
        if: false
        id: tag_release_candidate
        run: |
          tag='${{ needs.get_last_tag.outputs.next_tag_repo }}'
          message='${{ needs.get_last_tag.outputs.next_tag_repo }}'
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git tag -a "${tag}" -m "${message}"
          git push origin "${tag}"
          echo "TAG_RELEASE_CANDIDATE=$tag" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Create changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          ignorePreReleases: "true"
          fromTag: ${{ needs.get_last_tag.outputs.last_tag_repo }}
          toTag: ${{ needs.get_last_tag.outputs.next_tag_repo }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create PreRelease
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prerelease: true
          tag_name: '${{ needs.get_last_tag.outputs.next_tag_repo }}'
          release_name: '${{ needs.get_last_tag.outputs.next_tag_repo }}'
          body: |
            Actor: ${{ github.actor }}
            ActionRunner: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            ${{ steps.build_changelog.outputs.changelog }}
  promote_prd:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: generate_pre_release
    environment: promote_prd
    steps:
      - name: Promote prd step
        run: echo "waiting approve"

  generate_release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: promote_prd
    steps:
      - name: Generate release
        run: echo "Generate release OK"

  validate_deploy_prd:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: generate_release
    steps:
      - name: Validate deploy prd
        run: echo "validate deploy PRD OK"
